version: '3.1'
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123mudar
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres
    networks:
      - db-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"

networks:
  db-network:

volumes:
  db: